env:
   global:
     - CONAN_REFERENCE: "app/1.0.0-nightly"
     - CONAN_USERNAME: "grifcj"
     - CONAN_LOGIN_USERNAME: "grifcj"
     - CONAN_CHANNEL: "dev"
     - CONAN_UPLOAD: "https://api.bintray.com/conan/grifcj/learning"

linux: &linux
   os: linux
   dist: bionic
   language: python
   python: "3.7"
   services:
     - docker
matrix:
   include:
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=7.0 CONAN_DOCKER_IMAGE=conanio/clang7

      - <<: *linux
        env: CONAN_CLANG_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/clang8

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
