os: linux
language: python
python: "3.7"
dist: bionic
compiler:
  - clang
install:
  - pip install conan
  - conan user
  - conan remote add learning https://api.bintray.com/conan/grifcj/learning
  - conan install -if build . --build missing -pr travis.conan.yml
script:
  - conan build -bf build .
