os: linux
 services:
    - docker
 sudo: required
 language: python
 env:
   matrix:
     - DOCKER_IMAGE=conanio/clang7

 before_install:
   - ./.travis/before_install.sh

 install:
   - ./.travis/install.sh

 script:
   - ./.travis/run.sh
