os: linux
services:
   - docker
sudo: required
language: python
env:
   matrix:
      - DOCKER_IMAGE=conanio/clang7

script:
   - pip install conan
   - conan install -if build . -pr ./travis.conan.yml --build missing
   - conan build -bf build .
