language: python

services:
   - docker

before_install:
   - docker run -dit --name dconan -v $(pwd):/src conanio/clang7 bash

script:
   - docker attach dconan
   - cd /src
   - conan remote add learning https://api.bintray.com/conan/grifcj/learning
   - conan install -if build . -s compiler.libcxx=libstdc++11 --build missing
   - conan build -bf build .
