os: linux
language: python
python: "3.7"
dist: bionic
compiler:
  - gcc
install:
  - pip install conan
  - conan user
script:
  - conan install cmake_installer/3.15.4@conan/stable
  - conan install . -g virtualrunenv
  - source activate_run.sh
  - conan build .
