os: linux
language: python
python: "3.7"
dist: bionic
compiler:
  - gcc
install:
  - pip install conan
  - conan user
  - conan remote add learning https://api.bintray.com/conan/grifcj/learning
  - conan install -if build .
  - source build/activate_run.sh
  - conan install -if build . --build missing
script:
  # Build and test the app...
  - conan build -bf build .
